// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDypbqtl7m_Bl-w9H-ZKMeGCYF3yrudFIU',
    appId: '1:412329483794:web:ba9b7c9cb47130ea09c2cb',
    messagingSenderId: '412329483794',
    projectId: 'stackflow-b3cbf',
    authDomain: 'stackflow-b3cbf.firebaseapp.com',
    storageBucket: 'stackflow-b3cbf.firebasestorage.app',
    measurementId: 'G-ZFWKGBSMSF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsSDpI8UT5xblOndiK7CuAe7L9SuwMFMk',
    appId: '1:412329483794:android:90d4cbceeb2f0f9a09c2cb',
    messagingSenderId: '412329483794',
    projectId: 'stackflow-b3cbf',
    storageBucket: 'stackflow-b3cbf.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRaght4xX7L1hjOoQFvAfKkSKDljt6vNQ',
    appId: '1:412329483794:ios:ec984bf26a6cc91909c2cb',
    messagingSenderId: '412329483794',
    projectId: 'stackflow-b3cbf',
    storageBucket: 'stackflow-b3cbf.firebasestorage.app',
    iosBundleId: 'com.stackflow.stackflow',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRaght4xX7L1hjOoQFvAfKkSKDljt6vNQ',
    appId: '1:412329483794:ios:ec984bf26a6cc91909c2cb',
    messagingSenderId: '412329483794',
    projectId: 'stackflow-b3cbf',
    storageBucket: 'stackflow-b3cbf.firebasestorage.app',
    iosBundleId: 'com.stackflow.stackflow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDypbqtl7m_Bl-w9H-ZKMeGCYF3yrudFIU',
    appId: '1:412329483794:web:5a213085d9d35bee09c2cb',
    messagingSenderId: '412329483794',
    projectId: 'stackflow-b3cbf',
    authDomain: 'stackflow-b3cbf.firebaseapp.com',
    storageBucket: 'stackflow-b3cbf.firebasestorage.app',
    measurementId: 'G-T5P86R2C0K',
  );
}
